"use client";

import { useMemo } from "react";
import {
  BarChart3,
  Activity,
  ShieldAlert,
  Lock,
  Receipt,
} from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MetricCard } from "@/components/ui/metric-card";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingSkeleton } from "@/components/ui/loading-skeleton";
import { UsageProgress } from "@/components/domain/usage-progress";
import { DataTable, type Column } from "@/components/ui/data-table";
import { Badge } from "@/components/ui/badge";
import { useAuth, isAdminRole } from "@/lib/auth";
import {
  useAuditLogs,
  useUsageEvents,
  useUsageSummary,
} from "@/lib/queries";
import {
  formatCost,
  formatDateTime,
  formatNumber,
  titleize,
} from "@/lib/utils";
import type { AuditLogResponse, UsageEventResponse } from "@/types/api";

export default function UsageAdminPage() {
  const { user } = useAuth();
  const isAdmin = isAdminRole(user?.role);

  const usage = useUsageSummary();
  const auditLogs = useAuditLogs();
  const events = useUsageEvents();

  const totals = useMemo(() => {
    const items = events.data?.items ?? [];
    let inputTokens = 0;
    let outputTokens = 0;
    let cost = 0;
    let toolCalls = 0;
    const featureCounts: Record<string, number> = {};
    const providerCounts: Record<string, number> = {};
    for (const e of items) {
      inputTokens += e.input_tokens;
      outputTokens += e.output_tokens;
      cost += e.estimated_cost;
      toolCalls += e.tool_calls;
      featureCounts[e.feature] = (featureCounts[e.feature] ?? 0) + 1;
      if (e.provider) {
        providerCounts[e.provider] = (providerCounts[e.provider] ?? 0) + 1;
      }
    }
    return {
      inputTokens,
      outputTokens,
      cost,
      toolCalls,
      featureCounts,
      providerCounts,
    };
  }, [events.data]);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Usage & Admin"
        description="Quota usage, cost estimates, agent events, and the audit log."
      />

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <MetricCard
          label="Estimated cost"
          value={formatCost(totals.cost)}
          icon={Receipt}
          iconClassName="bg-amber-50 text-amber-600"
          isLoading={events.isLoading}
          hint="Sum of recent usage events"
        />
        <MetricCard
          label="Input tokens"
          value={formatNumber(totals.inputTokens)}
          icon={Activity}
          isLoading={events.isLoading}
          hint="From LLM calls"
        />
        <MetricCard
          label="Output tokens"
          value={formatNumber(totals.outputTokens)}
          icon={BarChart3}
          iconClassName="bg-emerald-50 text-emerald-600"
          isLoading={events.isLoading}
          hint="Generated by the agent"
        />
        <MetricCard
          label="Tool calls"
          value={formatNumber(totals.toolCalls)}
          icon={Activity}
          iconClassName="bg-sky-50 text-sky-600"
          isLoading={events.isLoading}
          hint="Across recent events"
        />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Plan quotas</CardTitle>
          <span className="text-[11px] text-slate-500 capitalize">
            {usage.data?.plan_code ? `${usage.data.plan_code} plan` : ""}
          </span>
        </CardHeader>
        <CardContent>
          {usage.isError ? (
            <ErrorState onRetry={() => usage.refetch()} />
          ) : usage.isLoading ? (
            <LoadingSkeleton lines={4} />
          ) : !usage.data || usage.data.quotas.length === 0 ? (
            <EmptyState
              title="No quota data"
              description="As the agent runs, quotas will populate here."
            />
          ) : (
            <div className="grid gap-3 md:grid-cols-2">
              {usage.data.quotas.map((q) => (
                <UsageProgress key={q.feature} quota={q} />
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>By feature</CardTitle>
          </CardHeader>
          <CardContent>
            <BreakdownList counts={totals.featureCounts} emptyLabel="No usage events" />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>By provider</CardTitle>
          </CardHeader>
          <CardContent>
            <BreakdownList counts={totals.providerCounts} emptyLabel="No provider data" />
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Audit log</CardTitle>
          <span className="text-[11px] text-slate-500">
            Admin only
          </span>
        </CardHeader>
        <CardContent className="p-0">
          {!isAdmin ? (
            <AdminOnlyNotice />
          ) : auditLogs.isError ? (
            <div className="p-4">
              <ErrorState onRetry={() => auditLogs.refetch()} />
            </div>
          ) : (
            <DataTable<AuditLogResponse>
              rows={auditLogs.data?.items ?? []}
              columns={AUDIT_COLUMNS}
              getKey={(row) => row.id}
              isLoading={auditLogs.isLoading}
              emptyTitle="No audit entries"
              emptyDescription="Decisions, document changes, and key actions will appear here."
            />
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recent usage events</CardTitle>
          <span className="text-[11px] text-slate-500">
            Admin only
          </span>
        </CardHeader>
        <CardContent className="p-0">
          {!isAdmin ? (
            <AdminOnlyNotice />
          ) : events.isError ? (
            <div className="p-4">
              <ErrorState onRetry={() => events.refetch()} />
            </div>
          ) : (
            <DataTable<UsageEventResponse>
              rows={events.data?.items ?? []}
              columns={EVENT_COLUMNS}
              getKey={(row) => row.id}
              isLoading={events.isLoading}
              emptyTitle="No usage events yet"
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function BreakdownList({
  counts,
  emptyLabel,
}: {
  counts: Record<string, number>;
  emptyLabel: string;
}) {
  const entries = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  if (entries.length === 0) {
    return <p className="text-xs text-slate-500">{emptyLabel}</p>;
  }
  const max = entries[0][1];
  return (
    <ul className="space-y-2">
      {entries.map(([key, count]) => {
        const pct = Math.round((count / max) * 100);
        return (
          <li key={key} className="text-xs">
            <div className="flex items-center justify-between">
              <span className="font-medium text-slate-900">{titleize(key)}</span>
              <span className="text-slate-500">{count} events</span>
            </div>
            <div className="mt-1 h-1.5 w-full overflow-hidden rounded-full bg-slate-100">
              <div
                className="h-full rounded-full bg-indigo-500 transition-all"
                style={{ width: `${pct}%` }}
              />
            </div>
          </li>
        );
      })}
    </ul>
  );
}

function AdminOnlyNotice() {
  return (
    <div className="m-4">
      <div className="flex items-start gap-3 rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
        <div className="flex h-8 w-8 items-center justify-center rounded-md bg-slate-200 text-slate-600">
          <Lock className="h-4 w-4" />
        </div>
        <div>
          <p className="text-sm font-semibold text-slate-900">
            Admin access required
          </p>
          <p className="text-xs text-slate-500">
            Ask an owner or admin to view audit logs and usage events.
          </p>
        </div>
        <ShieldAlert className="ml-auto h-4 w-4 text-amber-500" />
      </div>
    </div>
  );
}

const AUDIT_COLUMNS: Column<AuditLogResponse>[] = [
  {
    key: "when",
    header: "When",
    render: (row) => (
      <span className="text-xs text-slate-500">
        {formatDateTime(row.created_at)}
      </span>
    ),
  },
  {
    key: "action",
    header: "Action",
    render: (row) => (
      <Badge tone="primary">{titleize(row.action)}</Badge>
    ),
  },
  {
    key: "resource",
    header: "Resource",
    render: (row) => (
      <span className="text-sm">
        {row.resource_type}
        <span className="ml-1 text-[11px] text-slate-400">#{row.resource_id.slice(-8)}</span>
      </span>
    ),
  },
  {
    key: "user",
    header: "Actor",
    render: (row) => (
      <span className="font-mono text-[11px] text-slate-600">
        {row.user_id ?? "system"}
      </span>
    ),
  },
];

const EVENT_COLUMNS: Column<UsageEventResponse>[] = [
  {
    key: "when",
    header: "When",
    render: (row) => (
      <span className="text-xs text-slate-500">
        {formatDateTime(row.created_at)}
      </span>
    ),
  },
  {
    key: "feature",
    header: "Feature",
    render: (row) => <Badge tone="primary">{titleize(String(row.feature))}</Badge>,
  },
  {
    key: "model",
    header: "Model",
    render: (row) => (
      <span className="font-mono text-[11px] text-slate-600">
        {row.model ?? "—"}
      </span>
    ),
  },
  {
    key: "provider",
    header: "Provider",
    render: (row) => (
      <span className="text-xs text-slate-700">
        {row.provider ?? "—"}
        {row.fallback_used && (
          <Badge tone="warning" className="ml-1">
            fallback
          </Badge>
        )}
      </span>
    ),
  },
  {
    key: "tokens",
    header: "Tokens",
    render: (row) => (
      <span className="text-xs text-slate-700">
        {formatNumber(row.input_tokens + row.output_tokens)}
      </span>
    ),
  },
  {
    key: "cost",
    header: "Cost",
    render: (row) => (
      <span className="text-xs font-medium text-slate-900">
        {formatCost(row.estimated_cost)}
      </span>
    ),
  },
  {
    key: "latency",
    header: "Latency",
    render: (row) => (
      <span className="text-xs text-slate-500">{row.latency_ms}ms</span>
    ),
  },
];
